version: '3'
services:
  node:
    build: .
    command: bash
    volumes:
      - .:/home/me/app:delegated
    ports:
      - 8080:8080
    links:
      - mongo
    tty: true
    depends_on:
      - mongo
    environment:
      - PORT=8080
  mongo:
    image: mongo:3.4.8
    ports:
      - 27017:27017
